### ISSUE TITLE
While trying to install package i am facing the error.

### ISSUE THREAD

**Issue by trikesh** [justin-lau/ember-intl-tel-input#28]
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-57_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/which/which.js:13:12)\n    at F (/Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/which/which.js:68:19)\n    at E (/Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/which/which.js:80:29)\n    at /Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/which/which.js:89:16\n    at /Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/isexe/index.js:42:5\n    at /Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.1
gyp verb command install [ '8.9.1' ]
gyp verb install input version string "8.9.1"
gyp verb install installing version: 8.9.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.9.1
gyp verb ensuring nodedir is created /Users/12112211/.node-gyp/8.9.1
gyp verb created nodedir /Users/12112211/.node-gyp/8.9.1
gyp http GET https://nodejs.org/download/release/v8.9.1/node-v8.9.1-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.9.1' ]
gyp verb remove using node-gyp dir: /Users/12112211/.node-gyp
gyp verb remove removing target version: 8.9.1
gyp verb remove removing development files for version: 8.9.1
gyp ERR! configure error 
gyp ERR! stack Error: ENOENT: no such file or directory, open '/Users/12112211/Documents/Development/New Ember Application/samplePr/C:/devel/ret_root.crt'
gyp ERR! stack     at Object.fs.openSync (fs.js:646:18)
gyp ERR! stack     at Object.fs.readFileSync (fs.js:551:33)
gyp ERR! stack     at readCAFile (/Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/node-gyp/lib/install.js:466:15)
gyp ERR! stack     at download (/Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/node-gyp/lib/install.js:438:22)
gyp ERR! stack     at /Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/node-gyp/lib/install.js:185:19
gyp ERR! stack     at /Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/mkdirp/index.js:30:20
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:135:15)
gyp ERR! System Darwin 17.2.0
gyp ERR! command "/usr/local/bin/node" "/Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/ember-intl-tel-input/node_modules/node-sass
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/12112211/.npm/_logs/2017-12-12T08_52_35_790Z-debug.log

> node-sass@3.13.1 install /Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/ember-intl-tel-input/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-57_binding.node

> node-sass@3.13.1 postinstall /Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/ember-intl-tel-input/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=

    at Promise.all.then.arr (/Users/12112211/Documents/Development/New Ember Application/samplePr/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

----------------------
npm version  5.5.1
node version 8.9.1
ember version is 2.17.0
Python 2.7.10
I have node-sass version 4.5.2 installed in my PC as node 8 does not support 3.13.1.
Please let me know how to resolve this issue and install the "ember-intl-tel-input" .

**Comment by tomgazit** [comment]
I get the same error as well.

**Comment by cdatehortuab** [comment]
Hello, This project looks like is not currently mantained. I've made a fork of this project. Check it at [![Ember Observer Score](https://emberobserver.com/badges/ember-intl-tel-input2.svg)](https://emberobserver.com/addons/ember-intl-tel-input2) [https://emberobserver.com/addons/ember-intl-tel-input2](https://emberobserver.com/addons/ember-intl-tel-input2)
