### ISSUE TITLE
File not found ...\addon\styles\addon.scss

### ISSUE THREAD

**Issue by gcasanova** [justin-lau/ember-intl-tel-input#6]
After installing the addon and configuring it via the new ember-cli-build.js, I cannot build my ember application. It throws,

```
File not found: D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\addon\styles\addon.scss in any of the following include paths: D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\addon\styles

at Object.findFileSync (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\include-path-searcher\index.js:12:9)
at SassCompiler.<anonymous> (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\index.js:51:33)
at lib$rsvp$$internal$$initializePromise (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\rsvp\dist\rsvp.js:537:9)
at new lib$rsvp$promise$$Promise (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\rsvp\dist\rsvp.js:850:9)
at SassCompiler.updateCache (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\index.js:42:10)
at D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\broccoli-caching-writer\index.js:96:34
at lib$rsvp$$internal$$tryCatch (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\rsvp\dist\rsvp.js:489:16)
at lib$rsvp$$internal$$invokeCallback (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\rsvp\dist\rsvp.js:501:17)
at lib$rsvp$$internal$$publish (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\rsvp\dist\rsvp.js:472:11)
at lib$rsvp$asap$$flush (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\rsvp\dist\rsvp.js:1290:9)
```

I might be missing some important configuration setting, but I have certainly followed the simple guidelines of the addon. Did anyone else had this issue before? Thank  you

**Comment by justin-lau** [comment]
This addon have not supported `ember-cli` >= v1.13.0 yet, as there are still [bugs](https://github.com/ember-cli/ember-cli/issues/4435) around `the ember-cli-build.js` need fixed to get it working. The best you can do is to use `ember-cli` v0.2.7 for now. Stay tuned and when 1.13.2 is out I will look into this again.

**Comment by gcasanova** [comment]
Alright justin, thanks for the clarification, much appreciated. Nice work!

**Comment by justin-lau** [comment]
You're welcome =)

**Comment by gcasanova** [comment]
Hi justin,

 i just downgraded the project to ember-cli version 0.2.7 and I still get the same error. You might want to check this out, thank you anyways.

```
version: 0.2.7

A new version of ember-cli is available (1.13.1). To install it, type ember update.
Proxying to http://localhost:8080
Livereload server on port 35729
Serving on http://localhost:4200/

File not found: D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\addon\styles\addon.scss in any of the following include paths:
D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\addon\styles
Error: File not found: D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\addon\styles\addon.scss in any of the following include paths:
D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\addon\styles
at Object.findFileSync (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\include-path-searcher\index.js:12:9)
at SassCompiler.<anonymous> (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\index.js:51:33)
at lib$rsvp$$internal$$initializePromise (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\rsvp\dist\rsvp.js:537:9)
at new lib$rsvp$promise$$Promise (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\rsvp\dist\rsvp.js:850:9)
at SassCompiler.updateCache (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\index.js:42:10)
at D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\broccoli-caching-writer\index.js:96:34
at lib$rsvp$$internal$$tryCatch (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\rsvp\dist\rsvp.js:489:16)
at lib$rsvp$$internal$$invokeCallback (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\rsvp\dist\rsvp.js:501:17)
at lib$rsvp$$internal$$publish (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\rsvp\dist\rsvp.js:472:11)
at lib$rsvp$asap$$flush (D:\workspace\SocialDemand-Client\node_modules\ember-intl-tel-input\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\rsvp\dist\rsvp.js:1290:9)
```

**Comment by justin-lau** [comment]
I think I know what's going on here. This addon relies on [a bugfix branch of `ember-cli-sass`](https://github.com/aexmachina/ember-cli-sass/pull/57) to workaround some issues produced by `ember-cli`. It seems like it has difficulty looking up the correct Sass files on Windows.

Let me fire up a Windows machine and see if I can fix that today. Thanks for reporting!

**Comment by justin-lau** [comment]
@gcasanova I have updated the bugfix branch of `ember-cli-sass`, please try building again after a `npm install`.

**Comment by gcasanova** [comment]
Well, this one worked. Great job Justin, cheers ^^

**Comment by justin-lau** [comment]
Great :)
